'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'likes',
      [
        {
          userId: 1,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 1,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 2,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 3,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 4,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 5,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 6,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 7,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 8,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 9,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 10,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 11,
          postId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 10,
          postId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 11,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 10,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 12,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 11,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 51,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 55,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 61,
          postId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          userId: 111,
          postId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('likes', null, {});
  },
};
