'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert(
      'likes',
      [
        {
          postId: 1,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 6,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 1,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 2,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 3,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 4,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 5,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 6,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 7,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 8,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 9,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 1,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 2,
          userId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 3,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 4,
          userId: 19,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 5,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 7,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 16,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 17,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 8,
          userId: 18,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 11,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 12,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 13,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 14,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 15,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 111,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 112,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 113,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 114,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 115,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 116,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 117,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 118,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          postId: 9,
          userId: 119,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ],
      {},
    );
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('likes', null, {});
  },
};
